export const HEIGHT_WHEEL_ITEM_HEIGHT = 44;

export const HEIGHT_WHEEL_VISIBLE_COUNT = 3;

export const HEIGHT_WHEEL_PAD_COUNT = 1;

export const HEIGHT_WHEEL_VIEWPORT_HEIGHT = HEIGHT_WHEEL_ITEM_HEIGHT * HEIGHT_WHEEL_VISIBLE_COUNT;
