/** Consultation mock library for Storybook and offline craft preview. */
export const consultationMeals = [
    {
        id: 'meal-1',
        title: 'Egg white veggie scramble',
        imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',
        mealType: 'Breakfast',
        category: 'Breakfast',
        prepMinutes: 18,
        macros: { calories: 312, protein: '28g', carbs: '12g', fat: '16g' },
        tags: [
            { label: 'Breakfast', type: 'category' },
            { label: 'Keto', type: 'dietary' },
            { label: 'High Protein', type: 'dietary' },
        ],
        nutrientHighlights: ['B12', 'Iron'],
        caloriesNumber: 312,
    },
    {
        id: 'meal-1b',
        title: 'Chia protein overnight oats',
        imageUrl: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=900&q=80',
        mealType: 'Breakfast',
        category: 'Breakfast',
        prepMinutes: 8,
        macros: { calories: 380, protein: '26g', carbs: '44g', fat: '11g' },
        tags: [
            { label: 'Breakfast', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
            { label: 'High Protein', type: 'dietary' },
        ],
        nutrientHighlights: ['Magnesium'],
        caloriesNumber: 380,
    },
    {
        id: 'meal-2',
        title: 'Post-workout salmon bowl',
        imageUrl: 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=900&q=80',
        mealType: 'Meal',
        category: 'Meal',
        prepMinutes: 22,
        macros: { calories: 520, protein: '44g', carbs: '38g', fat: '22g' },
        tags: [
            { label: 'Meal', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
            { label: 'High Protein', type: 'dietary' },
        ],
        nutrientHighlights: ['Magnesium', 'Zinc'],
        caloriesNumber: 520,
    },
    {
        id: 'meal-2b',
        title: 'Herb chicken quinoa plate',
        imageUrl: 'https://images.unsplash.com/photo-1604908177225-6b9dd98ec605?auto=format&fit=crop&w=900&q=80',
        mealType: 'Meal',
        category: 'Meal',
        prepMinutes: 25,
        macros: { calories: 610, protein: '48g', carbs: '58g', fat: '19g' },
        tags: [
            { label: 'Meal', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
            { label: 'High Protein', type: 'dietary' },
        ],
        nutrientHighlights: ['Zinc'],
        caloriesNumber: 610,
    },
    {
        id: 'meal-2c',
        title: 'Ketogenic steak + greens',
        imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80',
        mealType: 'Meal',
        category: 'Meal',
        prepMinutes: 28,
        macros: { calories: 720, protein: '55g', carbs: '14g', fat: '46g' },
        tags: [
            { label: 'Meal', type: 'category' },
            { label: 'Ketogenic', type: 'dietary' },
            { label: 'High Protein', type: 'dietary' },
        ],
        nutrientHighlights: ['Iron'],
        caloriesNumber: 720,
    },
    {
        id: 'meal-2d',
        title: 'Hormone Feast turkey + sweet potato',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',
        mealType: 'Meal',
        category: 'Meal',
        prepMinutes: 26,
        macros: { calories: 640, protein: '46g', carbs: '62g', fat: '20g' },
        tags: [
            { label: 'Meal', type: 'category' },
            { label: 'Hormone Feast', type: 'dietary' },
        ],
        nutrientHighlights: ['B12'],
        caloriesNumber: 640,
    },
    {
        id: 'meal-2e',
        title: 'Mediterranean lamb mince bowls',
        imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=900&q=80',
        mealType: 'Meal',
        category: 'Meal',
        prepMinutes: 30,
        macros: { calories: 590, protein: '42g', carbs: '36g', fat: '28g' },
        tags: [
            { label: 'Meal', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
        ],
        nutrientHighlights: ['Iron', 'Zinc'],
        caloriesNumber: 590,
    },
    {
        id: 'meal-2f',
        title: 'Citrus prawn quinoa salad plate',
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80',
        mealType: 'Meal',
        category: 'Meal',
        prepMinutes: 24,
        macros: { calories: 505, protein: '38g', carbs: '48g', fat: '16g' },
        tags: [
            { label: 'Meal', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
            { label: 'High Protein', type: 'dietary' },
        ],
        nutrientHighlights: ['Selenium'],
        caloriesNumber: 505,
    },
    {
        id: 'meal-3',
        title: 'Side salad crunch bowl',
        imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80',
        mealType: 'Side salad',
        category: 'Side salad',
        prepMinutes: 10,
        macros: { calories: 260, protein: '8g', carbs: '18g', fat: '17g' },
        tags: [
            { label: 'Side salad', type: 'category' },
            { label: 'Vegan', type: 'dietary' },
        ],
        nutrientHighlights: ['Folate'],
        caloriesNumber: 260,
    },
    {
        id: 'meal-3b',
        title: 'Side salad — citrus kale',
        imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&q=80',
        mealType: 'Side salad',
        category: 'Side salad',
        prepMinutes: 9,
        macros: { calories: 240, protein: '7g', carbs: '20g', fat: '15g' },
        tags: [
            { label: 'Side salad', type: 'category' },
            { label: 'Vegan', type: 'dietary' },
        ],
        nutrientHighlights: ['Folate'],
        caloriesNumber: 240,
    },
    {
        id: 'meal-4',
        title: 'Soup of the day — lentil',
        imageUrl: 'https://images.unsplash.com/photo-1604908554238-3f9b9b0c4b6c?auto=format&fit=crop&w=900&q=80',
        mealType: 'Soup',
        category: 'Soup',
        prepMinutes: 16,
        macros: { calories: 430, protein: '26g', carbs: '62g', fat: '10g' },
        tags: [
            { label: 'Soup', type: 'category' },
            { label: 'Sickle Cell Anemia', type: 'dietary' },
        ],
        nutrientHighlights: ['Iron', 'Magnesium'],
        caloriesNumber: 430,
    },
    {
        id: 'meal-5',
        title: 'Dessert — yogurt berries',
        imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80',
        mealType: 'Dessert',
        category: 'Dessert',
        prepMinutes: 6,
        macros: { calories: 220, protein: '12g', carbs: '24g', fat: '8g' },
        tags: [
            { label: 'Dessert', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
        ],
        nutrientHighlights: ['B12'],
        caloriesNumber: 220,
    },
    {
        id: 'meal-5b',
        title: 'Dessert — cacao chia mousse',
        imageUrl: 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?auto=format&fit=crop&w=900&q=80',
        mealType: 'Dessert',
        category: 'Dessert',
        prepMinutes: 7,
        macros: { calories: 260, protein: '10g', carbs: '28g', fat: '13g' },
        tags: [
            { label: 'Dessert', type: 'category' },
            { label: 'Balanced', type: 'dietary' },
        ],
        nutrientHighlights: ['Magnesium'],
        caloriesNumber: 260,
    },
];
